[tool.poetry]
name = "blp"
version = "0.0.4"
description = "Simple blpapi wrapper"
authors = ["bissli <bissli@xyz.com>"]

[tool.poetry.dependencies]
python = "^3.10"

blpapi = { version = "*", source = "blpapi" }

pandas = "*"
pyarrow = "*"
numpy = "*"
opendate = ">=0.1.50"

pywin32 = { version = "*", markers = "sys_platform == 'win32'" }

libb-util = ">=0.0.61"

# == test
asserts = { version = "*", optional = true }
pytest = { version = "*", optional = true }

[tool.poetry.extras]
test = [
  "asserts",
  "pytest",
]

[[tool.poetry.source]]
name = "blpapi"
url = "https://blpapi.bloomberg.com/repository/releases/python/simple"
priority = "explicit"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
